# Generated by Django 5.1.2 on 2024-10-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
